#define HARDWARE_SETUP_COMMON_INCLUDED

#define RFID_READER_RESET_PIN 2
#define RFID_READER_1_PIN 3
#define RFID_READER_2_PIN 4
#define RFID_READER_3_PIN 5
#define NUM_OF_RFID_READERS 3

#define INDUCTION_SENSOR_PIN  6
#define METAL_FOUND           HIGH
#define NO_METAL_FOUND        LOW

#define FEEDBACK_LED_PIN  7

#define MAGNET_PIN    9
#define MAGNET_OPENED LOW
#define MAGNET_CLOSED HIGH

#define RFID_TAG_ID_OF_BOOK   "4529512210425144"
#define RFID_TAG_ID_OF_VIAL   "4529412210425144"
#define RFID_TAG_ID_OF_SNITCH "4527612210425144"

#define RFID_READER_INDEX_BOOK    0
#define RFID_READER_INDEX_VIAL    1
#define RFID_READER_INDEX_SNITCH  2

const byte RFID_READER_PINS[NUM_OF_RFID_READERS] = {RFID_READER_1_PIN, RFID_READER_2_PIN, RFID_READER_3_PIN};